### ISSUE TITLE
VisualDL升级建议

### ISSUE THREAD

**Issue by ShenYuhan** [ShaneTian/Induction-Networks#1]
您好，很高兴看到您的repo中使用了VisualDL进行可视化。
目前1.X版本的VisualDL已经停止维护，建议您使用2.X版本的VDL，目前的最新版本是2.0.0b6

新版的VDL从性能、易用性上都进行了极大的改进，并且处在高速迭代开发中，具体信息可以参考[VisualDL](https://github.com/PaddlePaddle/VisualDL)

同时有任何问题也欢迎您在VDL的issue上与我们交流。

**Comment by ShaneTian** [comment]
> 您好，很高兴看到您的repo中使用了VisualDL进行可视化。
> 目前1.X版本的VisualDL已经停止维护，建议您使用2.X版本的VDL，目前的最新版本是2.0.0b6
> 
> 新版的VDL从性能、易用性上都进行了极大的改进，并且处在高速迭代开发中，具体信息可以参考[VisualDL](https://github.com/PaddlePaddle/VisualDL)
> 
> 同时有任何问题也欢迎您在VDL的issue上与我们交流。

好的，谢谢！

本来打算用最新版的，但是好像发现现在还没有 histogram 功能？也提了一个 [issue](https://github.com/PaddlePaddle/VisualDL/issues/660)

等新功能完善了我再更新一下代码 :smile:

**Comment by ShenYuhan** [comment]
再次感谢关注VisualDL，`Histogram`正在紧锣密鼓的开发中，预计本周能够发布新版本，到时候可以参考我们的教程进行替换。😄

**Comment by ShaneTian** [comment]
赞 👍
